import React from "react";

export const language = {
  en: {
    homepage: {
      title: "Trading Room",
      subtitle: "the meet-up place for producers and buyers in agriculture",
      button: "Read more",
      sortingTab: {
        date: "Date",
        price: "Price",
        az: "A-Z",
      },
      filters: {
        location: "location",
        category: "category"
      
    }
    },
    adminDashboard: {
      orders: "Orders",
      user: "Manage Users",
      userList: "Manage Products<",
    },
    loginPage: {
      errorMessage: "Email/Password is incorrect",
      createAccountTitle: "Don't have an account yet?",
      signUp: "Sign Up",
      forgotPassword: "Forgot Password",
      login: "Login",
      register: "Register",
    },
    manageOrders: {
      bannerTitle: "Leads",
      bannerSubtitle: "*",
      headerClientName: "Client Name",
      headerProduct: "Product",
      headerQuantity: "Quantity",
      headerRequestDate: "Request Date",
      headerDetails: "Details",
    },
    manageProducts: {
      bannerTitle: "Products",
      bannerSubtitle: "manage all products",
      headerProductName: "Product Name",
      headerCategory: "Category",
      headerPriceUnit: "Price/Unit",
      headerStatus: "Status",
      headerDetails: "Details",
    },
    manageUsers: {
      bannerTitle: "User Management",
      bannerSubtitle: "All users list",
      headerClientName: "Client First Name",
      headerClientSurname: "Client Last Name",
      headerEmail: "E-mail",
      headerRole: "ROLE",
      headerDetails: "Details",
    },
    myDetails: {
      bannerTitle: "My Profile",
      bannerSubtitle: "update my details",
      lblId: "id",
      lblEmail: "e-mail",
      lblName: "name",
      lblSurname: "surname",
      lblPhone: "phone",
      lblCompany: "company",
      lblAddress: "address",
    },
    myOrders: {
      bannerTitle: "My Orders",
      bannerSubtitle: "see all your orders here",
      clientName: "Client Name",
      productsRequested: "Products Requested",
      email: "e-mail:",
      phone: "phone:",
      company: "company:",
      address: "address:",
    },
    orderPage: {
      bannerTitle: "My Orders",
      bannerSubtitle: "see all your orders here",
      clientName: "Client Name",
      productsRequested: "Products Requested",
      email: "e-mail:",
      phone: "phone:",
      company: "company:",
      address: "address:",
      description: "description:",
      price: "price:",
      quantity: "Quantity:",
      location: "location:",
    },
    productPage: {
      bannerTitle: "Products",
      bannerSubtitle: "product details",
      lblId: "id",
      lblName: "name",
      lblCategory: "category",
      lblCertification: "certification",
      lblDescription: "description",
      lblOrigin: "origin",
      lblPrice: "price",
      lblUnit: "unit",
    },
    publishProduct: {
      bannerTitle: "Publish Product",
      bannerSubtitle: "product details",
      lblName: "Name",
      errorName: "Name is required",
      lblCategory: "Category",
      errorCategory: "Category is required",
      lblDescription: "Description",
      errorDescription: "Description is required",
      lblCertification: "Certification",
      errorCertification: "Certification is required",
      lblQuantity: "Quantity (Kgs)",
      errorQuantity: "Quantity is required",
      lblDateProduced: "Manufactured Date",
      errorDateProduced: "Manufactured Date is required",
      lblDateExpires: "Best Before",
      errorDateExpires: "Expiry date is required",
      lblOrigin: "City and State",
      errorOrigin: "Origin is required",
      lblDateAvailable: "date available",
      errorDateAvailable: "Availability date is required",
      lblPrice: "Price (MZN/Kgs)",
      errorPrice: "Price is required",
      lblUnit: "unit",
      errorUnit: "Unit is required",
      chooseOption: "Choose your option",
      option1: "Option 1",
      option2: "Option 2",
      option3: "Option 3",
    },
    registerPage: {
      title: "Sign Up",
      subtitle: "Create an appload account",
      name: "First Name",
      errorName: "Name is required",
      surname: "Last Name",
      errorSurname: "Last Name is required",
      password: "password",
      errorPassword: "Password is required",
      confirmPassword: "Confirm Password",
      errorConfirmPassword: "Confirm password is required",
      email: "E-mail",
      errorEmail: "E-mail is required",
      phone: "Phone Number",
      errorPhone: "Phone Number is required",
      address: "Address",
      errorAddress: "Address is required",
      provinceTitle: "Province",
      country: "Country",
      countryDefault: "Mozambique",
      companyName: "Company Name",
      companyNuit: "Company NUIT/ITIN",
      hasAccount: "Already have an account?",
      signIn: "Sign In",
      signUp: "Sign Up",
    },
    userDashboard: {
      bannerTitle: "Leads",
      bannerSubtitle: "select a product that interest you",
      myOrders: "My Orders",
      accountDetails: "Account Details",
    },
    userPage: {
      bannerTitle: "Client Management",
      bannerSubtitle: "see client details",
      client: "Client",
      lblId: "id",
      lblEmail: "e-mail",
      lblName: "name",
      lblSurname: "surname",
      lblPhone: "phone",
      lblCompany: "company",
      lblAddress: "address",
      lblRole: "role",
      lblConfirmed: "confirmed",
    },
  },
  pt: {
    homepage: {
      title: "Trading Room",
      subtitle: "o ponto de encontro entre compradores e produtores agrícolas",
      button: "Saiba Mais",
      sortingTab: {
        date: "Data",
        price: "Preço",
        az: "A-Z",
      },
      filters: {
          location: "localização",
          category: "Categoria"
        
      }
    },
    adminDashboard: {
      orders: "Encomendas",
      user: "Gerir Utilizadores",
      userList: "Gerir Produtos",
    },
    loginPage: {
      errorMessage: "Email/Password está incorrecto",
      createAccountTitle: "Ainda não tem uma conta?",
      signUp: "Registe-se",
      forgotPassword: "Esqueceu a Password",
      login: "Login",
      register: "Registe-se",
    },
    manageOrders: {
      bannerTitle: "Oportunidades",
      bannerSubtitle: "*",
      headerClientName: "Nome do Cliente",
      headerProduct: "Produto",
      headerQuantity: "Quantidade",
      headerRequestDate: "Data da Encomenda",
      headerDetails: "Detalhes",
    },
    manageProducts: {
      bannerTitle: "Produtos",
      bannerSubtitle: "gerir todos os produtos",
      headerProductName: "Nome do Produto",
      headerCategory: "Categoria",
      headerPriceUnit: "Preço/Unidade",
      headerStatus: "Status",
      headerDetails: "Dados",
    },
    manageUsers: {
      bannerTitle: "Gestão do Utilizador",
      bannerSubtitle: "Lista de utilizadores",
      headerClientName: "Primeiro Nome do Cliente",
      headerClientSurname: "Último Nome do Cliente",
      headerEmail: "E-mail",
      headerRole: "FUNÇÃO",
      headerDetails: "Dados",
    },
    myDetails: {
      bannerTitle: "Perfil",
      bannerSubtitle: "actualizar os meus dados",
      lblId: "id",
      lblEmail: "e-mail",
      lblName: "nome",
      lblSurname: "sobrenome",
      lblPhone: "telefone",
      lblCompany: "empresa",
      lblAddress: "endereço",
    },
    myOrders: {
      bannerTitle: "As minhas Encomendas",
      bannerSubtitle: "ver todas as encomendas aqui",
      clientName: "Nome do Cliente",
      productsRequested: "Produtos Encomendados",
      email: "e-mail:",
      phone: "telefone:",
      company: "empresa:",
      address: "enderço:",
    },
    orderPage: {
      bannerTitle: "As minhas Encomendas",
      bannerSubtitle: "ver encomendas aqui",
      clientName: "Nome do Cliente",
      productsRequested: "Produtos Solicitados",
      email: "e-mail:",
      phone: "telefone:",
      company: "empresa:",
      address: "endereço:",
      description: "descrição:",
      price: "preço:",
      quantity: "Quantidade:",
      location: "localização:",
    },
    productPage: {
      bannerTitle: "Produtos",
      bannerSubtitle: "Dados do produto",
      lblId: "ID do produto",
      lblName: "Nome",
      lblCategory: "Categoria",
      lblCertification: "Certificação",
      lblDescription: "Descrição",
      lblOrigin: "Distrito e Província de origem",
      lblPrice: "Preço (MZN/Kgs)",
      lblUnit: "unidade",
      lblDateAvailable: "Disponível em",
      lblDateExpires: "Data de validade",
      lblDateProduced: "Data de produção",
      lblQuantity: "Quantidade (Kgs)",
    },
    publishProduct: {
      bannerTitle: "Publicar Produto",
      bannerSubtitle: "dados doproduto",
      lblName: "Nome",
      errorName: "Nome é um campo obrigatório",
      lblCategory: "Categoria",
      errorCategory: "Categoria é um campo obrigatório",
      lblDescription: "Descrição",
      errorDescription: "Descrição é um campo obrigatório",
      lblCertification: "Certificação",
      errorCertification: "Certificação é um campo obrigatório",
      lblQuantity: "Quantidade (Kgs)",
      errorQuantity: "Quantidade é um campo obrigatório",
      lblDateProduced: "Data de produção",
      errorDateProduced: "Data de produção é um campo obrigatório",
      lblDateExpires: "Data de Validade",
      errorDateExpires: "A Validade é um campo obrigatório",
      lblOrigin: "Distrito e Província de Origem",
      errorOrigin: "Origem é um campo obrigatório",
      lblDateAvailable: "Disponível em",
      errorDateAvailable: "A data de disponibilidade é um campo obrigatório",
      lblPrice: "Preço (MZN/Kgs)",
      errorPrice: "Preço é um campo obrigatório",
      lblUnit: "Unidade",
      errorUnit: "Unidade é é um campo obrigatório",
      chooseOption: "Seleccione a sua opção",
      option1: "Opção 1",
      option2: "Opção 2",
      option3: "Opção 3",
    },
    registerPage: {
      title: "Criar Conta",
      subtitle: "Crie uma conta appload",
      name: "Primeiro Nome",
      errorName: "Nome é um campo obrigatório",
      surname: "Último Nome",
      errorSurname: "Apelido é um campo obrigatório",
      password: "Palavra Passe",
      errorPassword: "Password é um campo obrigatório",
      confirmPassword: "Confirme a Palavra Passe",
      errorConfirmPassword: "Confirme a password é um campo obrigatório",
      email: "E-mail:",
      errorEmail: "E-mail é um campo obrigatório",
      phone: "Telefone",
      errorPhone: "Telefone é um campo obrigatório",
      address: "Endereço",
      errorAddress: "Endereço é um campo obrigatório",
      provinceTitle: "Provincia",
      country: "País",
      countryDefault: "Moçambique",
      companyName: "Nome da Empresa",
      companyNuit: "NUIT da Empresa",
      hasAccount: "Já tem conta na appload?",
      signIn: "Entrar",
      signUp: "Registar",
    },
    userDashboard: {
      bannerTitle: "Oportunidades",
      bannerSubtitle: "seleccione a mercadoria do seu interesse",
      myOrders: "Encomendas",
      accountDetails: "Dados da Conta",
    },
    userPage: {
      bannerTitle: "Gestão de Clientes",
      bannerSubtitle: "analise os dados do cliente",
      client: "Cliente",
      lblId: "identidade",
      lblEmail: "e-mail",
      lblName: "nome",
      lblSurname: "apelido",
      lblPhone: "telefone",
      lblCompany: "empresa",
      lblAddress: "endereço",
      lblRole: "função",
      lblConfirmed: "confirmado",
    },
  },
};

export const LangContext = React.createContext({
  lang: language.pt,
  toggleLang: () => {},
});
